name: Check and Clean M3U List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-playlist:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # لێرەدا مۆڵەتی 45 خولەک دەدەینە پڕۆسەکە تا بە ئارامی تەواو ببێت

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Blocklist Filter
        run: python build_playlist.py

      - name: Check and clean playlist
        run: node check-dead-channels.mjs

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Auto-removed blocked and dead channels" || exit 0
          git push
